---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: pruebas
  labels:
    app: mariadb
type: Opaque
data:
    MYSQL_ROOT_PASSWORD: cGFzc3dvcmQx
    MYSQL_USER: bWl1c3Vhcmlv
    MYSQL_PASSWORD: cGFzc3dvcmQy

---
apiVersion: v1
kind: Secret
metadata:
  name: tomcat-secret
  namespace: pruebas
type: Opaque
stringData:
    tomcat-users.xml: |-
        usuario: dGVzdAo=
        password: dGVzdAo=